[[redirects]]
  from = "/hopsfront/*"
  to = "/hopsfront/index.html"
  status = 200

[[headers]]
  for = "/hopsfront/*"
  [headers.values]
    "Service-Worker-Allowed" = "/hopsfront/"

[[headers]]
  for = "/hopsfront/manifest.webmanifest"
  [headers.values]
    "Content-Type" = "application/manifest+json" 